# docker compose --env-file ./backend/local.env up -d

services:
  postgres:
    container_name: shortener_postgres
    image: postgres:17.5-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    command: >
      postgres 
      -p ${POSTGRES_PORT}
    volumes:
      - shortner_vol:/data
    networks:
      - shortener_network
  
  backend:
    container_name: shortener_backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - shortener_network
    environment:
      - POSTGRES_USER=evans
      - POSTGRES_PASSWORD=evans
      - POSTGRES_PORT=3005
      - POSTGRES_HOST=postgres
      - POSTGRES_NAME=postgres
      - POSTGRES_USE_SSL=disable
  
  frontend:
    container_name: shortener_frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "5173:3000"
    depends_on:
      - backend
    networks:
      - shortener_network

volumes:
  shortner_vol: {}

networks:
  shortener_network: